install.packages("e1071")
install.packages("naivebayes")
install.packages("naivebayes")
library(e1071)
library(naivebayes)
NB = read.csv(file.choose())
NB1 = naiveBayes(buy~.,data=NB)
NBmodel = naive_bayes(buy ~ .,data = NB)
NBPredict = read.csv(file.choose())
NB = read.csv(file.choose())
NBPredict = read.csv(file.choose())
pred_class = predict(NB,newdata=NBPredict,type="class")
pred_class = predict(NB1,newdata=NBPredict,type="class")
NB = read.csv(file.choose())
NB
NB1 = read.csv(file.choose())
NBModel = naiveBayes(buy~.,data=NB)
library(e1071)
library(naivebayes)
NBModel = naiveBayes(buy~.,data=NB)
pred_class = predict(NBModel,newdata=NB1,type="class")
pred_class
NBModel1 = naive_bayes(buy~.,data=NB)
pred_raw = predict(NBModel1,newdata = NB1,type = "raw")
pred_raw = predict(NBModel1,newdata=NB1,type="raw")
pred_raw = predict(NBModel,newdata=NB1,type="raw")
pred_raw
pred_class = predict(NBModel1,newdata=NB1,type="class")
pred_class = predict(NBModel,newdata=NB1,type="class")
